# Generated by Django 4.0.2 on 2022-04-16 19:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='store_name')),
            ],
            options={
                'db_table': 'store',
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('purchase_on', models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='purchase_on')),
                ('price', models.IntegerField(verbose_name='total_price')),
                ('store_name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='apiv1.store')),
            ],
            options={
                'db_table': 'cost',
            },
        ),
    ]
